# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Saxxon
tagline:          'All Things Cybersecurity'
description:      'Explore the Unexplored'
url:              https://saxonyu.github.io/
baseurl:          ''

author:
  name:           'Yongjie Yu'
  linkedin_url:   'https://www.linkedin.com/in/yongjie-yu-554830262/'         

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SaxonYu/saxonyu.github.io

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-toc

# Enable TOC by default
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      toc: true

# Google Analytics
google_analytics: G-D5PTY2GKTV